### ISSUE TITLE
Unexpected error while trying to send NOT token

### ISSUE THREAD

**Issue by invizbyri** [mytonwalletorg/mytonwallet#104]
![photo_2024-06-22_17-19-45](https://github.com/mytonwalletorg/mytonwallet/assets/17267951/1558b434-cf25-44f0-a5e6-183a4a769719)
![Снимок экрана 2024-06-22 в 17 20 50](https://github.com/mytonwalletorg/mytonwallet/assets/17267951/0002cfda-ac97-4d41-a2c2-06590699866b)
![Снимок экрана 2024-06-22 в 17 21 33](https://github.com/mytonwalletorg/mytonwallet/assets/17267951/b8be8b86-4fc2-461d-bf5b-80fa86acb9cb)
Ошибка при попытке отправить токены NOT, ошибка наблюдается в веб-версии и в мобильном приложении: unexpected error после подтверждения ввода пароля.
При попытке обмена вечно висит awaiting previous fee.
Прошу помочь, токены застряли

**Comment by Moormemar** [comment]
جون مادرتون  این  نات کوین من را پس بدین.خدا از شما نمیگذره ۲۰روزه زندگی من شد اه و اشک و غصه

**Comment by Pakrohk** [comment]
Here's the English translation of the provided text:

To be able to swipe without problems in the TON network, the following steps are necessary:

1. Deposit some TON into your account
2. Perform a transaction, meaning some currency must be sent from your wallet
3. Make sure to leave enough for the network fee

Good luck, your problem is solved and you won't encounter unexpected errors anymore.
These steps also work for people whose money has been unified in the network, so don't worry.

**Comment by mytonwalletorg** [comment]
This should be fixed by now.
