### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by Kadeluxe** [mytonwalletorg/mytonwallet#20]
https://habr.com/ru/articles/727278/

**Comment by mytonwalletorg** [comment]
We published [a response](https://habr.com/ru/articles/727278/#comment_25413586) to the original topic.

**Comment by mytonwalletorg** [comment]
There are no logical errors or lies. Even if the React Native stack was highlighted by the HR for some reason — likely as a matter of targeting and distributing the developer search — it was not required by the publicly available task, which was clearly obvious from the task itself. Also, the candidate had all possible options to address his doubts, if any, but he never did, although we offered an introduction call with us. Anyways, it is not related to the dispute at all, as, in fact, it has not anyhow affected the evaluation of his task. 

There are clear instructions on which fixes were needed to nominate for compensation — in both the original task and our evaluation notions. We have never refused to pay. All he needed to do to receive compensation was to apply a few fixes to complete his work as per the task description. There were not many of them, but the developer refused to fix them and did not try to address his complaints directly or ask for explanations. 

He instead decided to bring it up in public with contradictory arguments and offensive accusations, which produced a form of flashmob by several other people and resulted in instantaneous downvotes, offensive statements, hateful speech, and attempts to disgrace our company and even the product by people who mostly did not even bother to get themself familiar with the case or read through the screenshots.

Even after that, we were seeking a direct conversation with the candidate to resolve the existing misunderstanding and discuss possible solutions — as we are still ready to fulfill our commitments — but he rejected us again. So, the question you posed seems quite legit to me. Why not just be good people?

**Comment by AlexanderMishutkin** [comment]
> Even after that, we were seeking a direct conversation with the candidate to resolve the existing misunderstanding and discuss possible solutions — as we are still ready to fulfill our commitments — but he rejected us again. 

In your comments under the post and everywhere you would better appeal to this fact.  since it is really irresponsible on the part of the author, having caused such a public outcry, not to negotiate.

On the opposite the fact that author's project did not meet all the requirements, fixes and fixes after fixes does not inspire any sympathy to your company. Such process of called contract work, not test task, and almost usually require an advanced payment.

On the end, I want to add, that the "viral" popularity of this incident is not a troll attack on your company.  It's the reflection of a problem of the industry that the recruiters does not care about candidates time, use some shotgun methods. As you see it cause frustration of both the employees and employers.

**Comment by mytonwalletorg** [comment]
"Fixes and fixes after fixes" may be a general industry problem or something that most people would want to see in this case rather than what it actually was. The test task was clearly outlined, and our feedback was consistent and strictly related to the missing bits of the original task.

The essential misunderstanding, in this case, is that the candidate and most commenters had a false assumption that the task is set to be paid on an attempt or spent time basis. But in fact, it was clearly set that the task needs to be fully completed with respect to our main criteria, and the successful completion of the task was a requirement for joining the company.

Since there was a chance that several developers could provide great results, and we were limited in our open positions, we decided to grant a compensation payment to everybody who would indeed succeed with the task but for some reason would not be able to join us. And it was also clearly outlined in the task document.

There may be other approaches to the recruitment process – such as technical interviews or CV assessments, which we totally respect. We assume that any company can choose a preferred method, and any candidate is free to accept it or not. In our case, we chose to announce a publicly available task for everybody to consider. There was absolutely no push or need to work on it unless a person wanted to do so.

We appreciate this rational conversation as well as any other honest attempt to resolve the underlying issues. Unfortunately, it has been practically impossible to discuss the case with the post author and community commenters, as the community turned out to be completely one-sided and aggressively ignorant of our position. Even independent community members who were in some way arguing or questioning the mass opinion were aggressively shamed and downvoted.

You can even look at this issue title – it was created by an unknown and unrelated person in such an irresponsible manner, and we received this hate everywhere, even on our product store page. 

We understand that people may have differing opinions, so thank you for reading this and trying to bring some rational and constructive perspective to the discussion.
