### ISSUE TITLE
Transfer consistently declined when using Ledger to transfer TON to other wallet

### ISSUE THREAD

**Issue by bits4fun** [mytonwalletorg/mytonwallet#35]
App is installed on Ledger Nano X, latest version available via developer mode. The app is saying "Ton is ready".
See video attachment.

MyTonWallet v1.16.4 was used.
This is the transaction that show the 10 TON received on the address of the Ledger Wallet. I was trying to "send it back":
https://tonscan.org/address/UQAjwkd5voNy4UFaTssjodL6llJ1PQmOzhemfbOQ7nzZIilc#transactions

https://github.com/mytonwalletorg/mytonwallet/assets/2035390/22b7c33c-a645-4297-b23e-f7f0ee8d577b

I have tried the same Desktop version (v1.16.4) on Mac and Linux (appImage), same error response.

**Comment by Moormemar** [comment]
سلام من۲۹۳۷۹نات کوین انتقال دادم۴روزه ولی نیومده بحسابم

**Comment by mytonwalletorg** [comment]
> سلام من۲۹۳۷۹نات کوین انتقال دادم۴روزه ولی نیومده بحسابم


Hello,

Please refer to https://t.me/MyTonWalletSupport.

**Comment by Moormemar** [comment]
مراجعه کردم ولی کمکی دریافت نکردم.این تمام سرمایه منه لطفا کمک کنید

**Comment by Moormemar** [comment]
لطفا کمکم کنید من با این پول میخواستم هزینه دانشگاه فرزندم را پرداخت
کنم.لطفااین ارز دیجیتال من را برگردانید لطفا لطفا piliz


در تاریخ جمعه ۷ ژوئن ۲۰۲۴،‏ ۱۲:۳۶ mytonwalletorg ***@***.***>
نوشت:

**Comment by Moormemar** [comment]
کانال تلگرام هیچ کس پاسخگو نیست لطفا

**Comment by mytonwalletorg** [comment]
> کانال تلگرام هیچ کس پاسخگو نیست لطفا

They will respond, eventually.

**Comment by Moormemar** [comment]
لطفا بگین چکار کنم

در تاریخ سه‌شنبه ۱۱ ژوئن ۲۰۲۴،‏ ۱۶:۱۱ mytonwalletorg <
***@***.***> نوشت:

**Comment by Moormemar** [comment]
سلام

در تاریخ جمعه ۱۴ ژوئن ۲۰۲۴،‏ ۰۰:۴۷ Moorteza ***@***.***> نوشت:

**Comment by Pakrohk** [comment]
Here's the English translation of the provided text:

To be able to swipe without problems in the TON network, the following steps are necessary:

1. Deposit some TON into your account
2. Perform a transaction, meaning some currency must be sent from your wallet
3. Make sure to leave enough for the network fee

Good luck, your problem is solved and you won't encounter unexpected errors anymore.
These steps also work for people whose money has been unified in the network, so don't worry.
